embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/water/assets/mesh/uniform_high_poly_plane.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"default\"\n"
  "  material: \"/water/material/stylized_water.material\"\n"
  "  textures {\n"
  "    sampler: \"foam_texture\"\n"
  "    texture: \"/water/assets/textures/default_foam_caustics_shallow.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"sparkle_normal_map\"\n"
  "    texture: \"/water/assets/textures/default_sparkle_normal.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"wave_normal_map\"\n"
  "    texture: \"/water/assets/textures/waves_large.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"reflection_cubemap\"\n"
  "    texture: \"/example/components/day_skybox.cubemap\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"edge_foam_texture\"\n"
  "    texture: \"/water/assets/textures/default_water_foam.png\"\n"
  "  }\n"
  "}\n"
  "create_go_bones: false\n"
  ""
}
